export const PATH = {
  BASE_URL: "/",
  DASHBOARD: "/dashboard",
  COMPANY: "/company/list",
  // EMPLOYEE: '/employee',
  // CHANGEPASS: "/profile/changepassword",
  PROFILE: "/profile",
  LOGIN: "/login",
  // USER: "/company/list",
  SITES: "/manage/sites",
  SITELIST: "/manage/sites/list",
  LOCATION: "/manage/location",
  LOCATIONLIST: "/manage/location/list",
  ZONES: "/manage/zones",
  ZONELIST: "/manage/zones/list",
  SERVEYLIST: "/servey/list",
  SERVEY: "/servey",
  FEDDACKOPTIONLIST: "/feedbackoptions/list",
  QUESTIONLIST: "/questions/list",
  MONITORFORM: "/monitor",
  MONITORLIST: "/monitor/list",
  MANAGEUSER: "/manageuser/list",
  MANAGEUSERLIST: "/manageuser/list",
  RATINGLIST: "/ratinglist",
};
